version: '3.7'

services:
    web:
        build: ./interintel
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - ./interintel/:/usr/src/app/
        ports:
        - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=intel
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=search_db
            
volumes: 
    postgres_data:            