version: '3.7'

services:
    web:
        build: ./interintel
        volumes:
            - ./interintel/:/usr/src/app/
            - static:/static
        ports:
            - "8000:8000"
        depends_on: 
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=search_db
    nginx:
        build: ./nginx
        ports:
            - "1337:80"
        volumes:
            - static:/static    
        depends_on:
            - web            
volumes: 
    postgres_data:
    static:            